AicrowdBadge.create!([
  {name: "Trustable", description: "Has Filled his profile page", badge_type_id: 3, code: "@participant.add_badge(\"Trustable\")", badges_event_id: 4, image: nil},
  {name: "gold-submitter", description: "Has made more than 1000 successful submissions", badge_type_id: 1, code: "if grading_status_cd == 'graded'\r\n  participant_submission_count = Submission.where(participant_id: participant_id, grading_status_cd: 'graded').count\r\n  if participant_submission_count == 1000\r\n    Participant.find_by(id: participant_id).add_badge(\"gold-submitter\")\r\n  end\r\nend", badges_event_id: 3, image: nil},
  {name: "Beginner", description: "Has made first submission", badge_type_id: 4, code: "if Submission.where(participant_id: participant_id).count == 1\r\n  Participant.find_by(id: participant_id)&.add_badge(\"Beginner\")\r\nend", badges_event_id: 3, image: nil},
  {name: "Learner", description: "Has made first successful submission", badge_type_id: 4, code: "if Submission.where(participant_id: participant_id, grading_status_cd: 'graded').count == 1\r\n  Participant.find_by(id: participant_id)&.add_badge(\"Learner\")\r\nend", badges_event_id: 3, image: nil},
  {name: "silver-submitter", description: "Has made more than 100 successful submissions", badge_type_id: 2, code: "if grading_status_cd == 'graded'\r\n  participant_submission_count = Submission.where(participant_id: participant_id, grading_status_cd: 'graded').count\r\n  if participant_submission_count == 100\r\n    Participant.find_by(id: participant_id).add_badge(\"silver-submitter\")\r\n  end\r\nend", badges_event_id: 3, image: nil},
  {name: "bronze-submitter", description: "Has made more than 10 submissions", badge_type_id: 3, code: "if grading_status_cd == 'graded'\r\n  participant_submission_count = Submission.where(participant_id: participant_id, grading_status_cd: 'graded').count\r\n  if participant_submission_count == 10\r\n    Participant.find_by(id: participant_id).add_badge(\"bronze-submitter\")\r\n  end\r\nend", badges_event_id: 3, image: nil},
  {name: "New User of the Month", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "First Onebox", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Wiki Editor", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "First Reply By Email", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Licensed", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Editor", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "First Emoji", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Certified", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "First Quote", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Aficionado", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "First Flag", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Popular Link", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Anniversary", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Regular", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Member", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Enthusiast", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "First Like", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "First Link", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Reader", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Read Guidelines", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Devotee", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "First Share", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Promoter", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Campaigner", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Basic User", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Leader", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Champion", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Nice Share", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Good Share", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Great Share", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Autobiographer", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Nice Post", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Good Post", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Great Post", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Nice Topic", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Good Topic", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Great Topic", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Hot Link", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Famous Link", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Appreciated", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Respected", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Admired", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Thank You", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Gives Back", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Empathetic", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Out of Love", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Higher Love", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Crazy in Love", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "First Mention", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "Welcome", description: nil, badge_type_id: nil, code: nil, badges_event_id: 5, image: nil},
  {name: "test_badge", description: "test", badge_type_id: 1, code: "", badges_event_id: 1, image: "aicrowd-logo--vertical.png"},
  {name: "silver-challenge-end", description: "Silver Medal winner for a challenge", badge_type_id: 2, code: "if max_rank <= 250\r\n  if participant_ranks>=0.1 && participant_ranks < 0.2\r\n    Participant.find_by(id: participant_id).add_badge('silver-challenge-end', {challenge_round: round_id})\r\n  end\r\nelsif max_rank > 250\r\n  if participant_ranks >= 0.01 && participant_ranks < 0.05\r\n    Participant.find_by(id: participant_id).add_badge('silver-challenge-end', {challenge_round: round_id})\r\n  end\r\nend", badges_event_id: 6, image: nil},
  {name: "gold-challenge-end", description: "Gold Medal winner for a challenge", badge_type_id: 1, code: "if max_rank <= 250\r\n  if participant_ranks>=0.2 && participant_ranks < 0.4\r\n    Participant.find_by(id: participant_id).add_badge('gold-challenge-end', {challenge_round: round_id})\r\n  end\r\nelsif max_rank > 250\r\n  if participant_ranks >=0.05 && participant_ranks < 0.1\r\n    Participant.find_by(id: participant_id).add_badge('gold-challenge-end', {challenge_round: round_id})\r\n  end\r\nend", badges_event_id: 6, image: nil},
  {name: "bronze-challenge-end", description: "Bronze Medal winner for challenge", badge_type_id: 3, code: "if max_rank <= 250\r\n  if participant_ranks < 0.1\r\n    Participant.find_by(id: participant_id).add_badge('bronze-challenge-end', {challenge_round: round_id})\r\n  end\r\nelsif max_rank > 250\r\n  if participant_ranks < 0.01\r\n    Participant.find_by(id: participant_id).add_badge('bronze-challenge-end', {challenge_round: round_id})\r\n  end\r\nend\r\n", badges_event_id: 6, image: nil}
])
