# frozen_string_literal: true

source 'https://rubygems.org'

# Rails assets gems
source 'https://rails-assets.org' do
  gem 'rails-assets-isInViewport'
  gem 'rails-assets-jQuery-File-Upload'
end

ruby '2.5.5'
gem 'rails', '5.2.2.1'

gem 'activeadmin', '1.4.3'
gem 'active_model_serializers'
gem 'activerecord-import'
gem 'ahoy_matey'
gem 'authtrail'
gem 'aws-sdk', '~> 2.2'
gem 'blazer'
gem 'bootstrap', '~> 4.3.1'
gem 'browser'
gem 'carrierwave', '~> 2.0'
gem 'chartkick'
gem 'ckeditor'
gem 'client_side_validations', '~> 17.0'
gem 'cocoon'
gem 'codemirror-rails'
gem 'coffee-rails'
gem 'country_select'
gem 'crowdai_admin'
gem 'csv'
gem 'dalli', '~> 2.7', '>= 2.7.10' # Memcache client
gem 'devise', '~> 4.7', '>= 4.7.1'
gem 'doorkeeper', '~> 5.0.3'
gem 'figaro'
gem 'file_validators'
gem 'fog'
gem 'font-awesome-rails'
gem 'friendly_id', '~> 5.1.0'
gem 'gibbon'
gem 'groupdate'
gem 'include_media_rails'
gem 'inline_svg'
gem 'jbuilder'
gem 'jquery-atwho-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'kaminari'
gem 'kramdown'
gem 'local_time'
gem 'lodash-rails'
gem 'loofah', '>= 2.2.3'
gem 'mini_magick'
gem 'mini_racer'
gem 'momentjs-rails', '~> 2.9'
gem 'net-ssh'
gem 'oj', '~> 3.0'
gem 'omniauth-facebook'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
gem 'omniauth-oauth2-generic'
gem 'paper_trail', '~> 10.3', '>= 10.3.1'
gem 'pg'
gem 'prometheus-client'
gem 'puma', '~> 4.3'
gem 'pundit'
gem 'rack', '>= 2.0.6'
gem 'rack-cors'
gem 'ransack'
gem 'recaptcha'
gem 'remotipart'
gem 'rollbar'
gem 'roo'
gem 'rouge'
gem 'rubyzip', '~> 1.2.2'
gem 'rufus-scheduler', '~> 3.4.0'
gem 'safely_block', '~> 0.2.2'
gem 'sanitize', '~> 5.2'
gem 'sass-rails'
gem 'scenic', '~> 1.3'
gem 'select2-rails'
gem 'sidekiq', '~> 5.1.1'
gem 'sidekiq-cron', '~> 0.6.3'
gem 'sidekiq-failures'
gem 'sidekiq-history'
gem 'sidekiq-unique-jobs', '~> 6.0', '>= 6.0.20'
gem 'simple_enum'
gem 'sinatra', '~> 2.0.2', require: nil
gem 'skylight', '~> 3.0'
gem 'social-share-button'
gem 'sprockets'
gem 'stringex'
gem 'turbolinks', '~> 5.1'
gem 'uglifier', '~> 4.1.10'
gem 'validate_url'
gem 'valid_email2'
gem 'webpacker', '~> 2.0'

# HTTP clients
gem 'faraday', '~> 1.0'
gem 'faraday_middleware', '~> 1.0'
gem 'http'
gem 'httparty'

gem 'irbtools', require: 'irbtools/binding'

# ACE editor
gem 'ace-rails-ap'

group :development do
  gem 'brakeman', require: false
  gem 'derailed_benchmarks'
  gem 'guard'
  gem 'letter_opener'
  gem 'lol_dba'
  gem 'meta_request'
  gem 'model_2_factory-rails'
  gem 'rails-erd'
  gem 'rubocop', '~> 0.88.0'
  gem 'scss_lint', require: false
  gem 'sdoc', '~> 0.4.0'
  gem 'seed_dump'
  gem 'stackprof'
  gem 'web-console'
end

group :development, :test do
  gem 'byebug'
  gem 'ffaker'
  gem 'oauth2'
  gem 'parallel_tests'
  gem 'pry-byebug'
  gem 'rspec-kickstarter'
  gem 'rspec-rails', '~> 4.0', '>= 4.0.1'
  gem 'spring'
  gem 'table_print'
end

group :test do
  gem 'capybara', '~> 3.33'
  gem 'capybara-screenshot'
  gem 'factory_bot_rails'
  gem 'launchy'
  gem 'nokogiri' # , '~> 1.8'
  gem 'pundit-matchers', git: 'https://github.com/crowdAI/pundit-matchers'
  gem 'rails-controller-testing'
  gem 'selenium-webdriver'
  gem 'simplecov', require: false
  gem 'timecop'
  gem 'vcr', '~> 5.0'
  gem 'webdrivers'
  gem 'webmock', '~> 3.7', '>= 3.7.6'
end

gem 'aicrowd_evaluations', git: 'http://gitlab.aicrowd.com/aicrowd/evaluations-api-clients.git', branch: 'rails', glob: 'ruby/*.gemspec'
